# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-06 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=datetime.datetime(2018, 5, 6, 14, 14, 5, 652532, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
